- name: patch powertools repo
  replace:
    path: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
    regexp: '(\s+)enabled\=0(\s+.*)?$'
    replace: '\1enabled=1\2'
    backup: yes

- name: install packages
  tags: package
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - lvm2
    - openstack-cinder
    - targetcli 
    - python3-oslo-policy
    - python3-keystonemiddleware

- name: clean volume group
  command: vgremove cinder-volumes -y
  ignore_errors: True

- name: clean pv disk
  command: pvremove -y -ff {{ cinder_dev }}
  ignore_errors: True

- name: create volume
  command: pvcreate -y -ff {{ cinder_dev }}

- name: create volume group
  command: vgcreate cinder-volumes {{ cinder_dev }}

- name: install cinder configuration
  tags: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/cinder/{{ item }}"
  with_items:
    - cinder.conf

- name: start services
  tags: service
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  when: not ansible_check_mode
  with_items:
    - openstack-cinder-volume
    - target
