- name: install packages
  tags: package
  package: name={{ item }} state=latest
  with_items:
    - lvm2
    - openstack-cinder
    - targetcli 
    - python-oslo-policy
    - python-keystonemiddleware

- name: clean volume group
  command: vgremove cinder-volumes -y
  ignore_errors: True

- name: clean pv disk
  command: pvremove -y -ff {{ cinder_dev }}
  ignore_errors: True

- name: create volume
  command: pvcreate -y -ff {{ cinder_dev }}

- name: create volume group
  command: vgcreate cinder-volumes {{ cinder_dev }}

- name: install cinder configuration
  tags: config
  template: src={{ item }}.j2 dest=/etc/cinder/{{ item }}
  with_items:
    - cinder.conf

- name: start services
  tags: service
  service: name={{ item }} state=restarted enabled=yes
  when: not ansible_check_mode
  with_items:
    - lvm2-lvmetad
    - openstack-cinder-volume
    - target
