- name: patch powertools repo
  replace:
    path: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
    regexp: '(\s+)enabled\=0(\s+.*)?$'
    replace: '\1enabled=1\2'
    backup: yes

- name: node install packages
  tags: package
  package: name={{ item }} state=latest
  with_items:
    - openstack-swift-account
    - openstack-swift-container
    - openstack-swift-object
    - rsync
    - rsync-daemon
    - xfsprogs

- name: install rsync configuration
  tags: config
  template: src={{ item }}.j2 dest=/etc/{{ item }}
  with_items:
    - rsyncd.conf

- name: start services
  tags: service
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - rsyncd

- name: install swift configuration
  tags: config
  template: src={{ item }}.j2 dest=/etc/swift/{{ item }}
  with_items:
    - account-server.conf
    - container-server.conf
    - object-server.conf
    - swift.conf

- name: install directories
  tags: config
  file: dest={{ swift_storage_dir }} owner=swift group=swift state=directory
  when: not ansible_check_mode

- name: install directories
  tags: config
  file: dest=/var/cache/swift owner=root group=swift state=directory mode=0775
  when: not ansible_check_mode

- name: prepare storage
  file: dest={{ swift_storage_dir }}/{{ item|basename }} state=directory owner=swift
  with_items: "{{ swift_storage_devices }}"
  when: item.find('/dev') < 0 and not ansible_check_mode

- name: try to umount disk if has mounted
  command: umount -f {{ swift_storage_dir }}/{{ item|basename }}
  with_items: "{{ swift_storage_devices }}"
  ignore_errors: True

- name: create filefs
  command: truncate -s {{ swift_device_size }} {{ item }}
  with_items: "{{ swift_storage_devices }}"
  when: item.find('/dev') < 0 and not ansible_check_mode

- name: create fs
  command: mkfs.xfs -f {{ item }}
  with_items: "{{ swift_storage_devices }}"
  when:  not ansible_check_mode

- name: mount
  mount:
    name: "{{ swift_storage_dir }}/{{ item|basename }}"
    src: "{{ item }}"
    fstype: xfs
    opts: "noatime,nodiratime,logbufs=8"
    state: mounted
  with_items: "{{ swift_storage_devices }}"
  when: not ansible_check_mode

- name: fix permissions
  file: dest={{ swift_storage_dir }} owner=swift group=swift mode=0775 recurse=yes
  when: not ansible_check_mode

- name: copy ring config
  tags: copy
  copy: src={{ inventory_dir }}/workdir/{{ item }} dest=/etc/swift/{{ item }}
  with_items:
    - account.ring.gz
    - container.ring.gz
    - object.ring.gz

- name: node start services
  tags: service
  service: name={{ item }} state=restarted enabled=yes
  when: not ansible_check_mode
  with_items:
    - rsyslog
    - openstack-swift-account
    - openstack-swift-account-auditor
    - openstack-swift-account-reaper
    - openstack-swift-account-replicator
    - openstack-swift-container
    - openstack-swift-container-auditor
    - openstack-swift-container-replicator
    - openstack-swift-container-updater
    - openstack-swift-object
    - openstack-swift-object-auditor
    - openstack-swift-object-replicator
    - openstack-swift-object-updater
