- name: install packages
  tags: package
  package: name={{ item }} state=latest
  with_items:
    - openstack-neutron 
    - openstack-neutron-linuxbridge 
    - ebtables
    - ipset
    - openstack-manila-share
    - python2-PyMySQL

- name: install manila configuration
  tags: config
  template: src={{ item }}.j2 dest=/etc/manila/{{ item }}
  with_items:
    - manila.conf

- name: install neutron configurations
  tags: config
  template: src={{ item }}.j2 dest=/etc/neutron/{{ item }}
  with_items:
    - neutron.conf

- name: install linuxbridge configurations
  tags: config
  template: src=linuxbridge_agent.ini.j2 dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini

- name: start services
  tags: service
  service: name={{ item }} state=restarted enabled=yes
  when: not ansible_check_mode
  with_items:
    - openstack-manila-share
    - neutron-linuxbridge-agent
