- name: patch powertools repo
  replace:
    path: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
    regexp: '(\s+)enabled\=0(\s+.*)?$'
    replace: '\1enabled=1\2'
    backup: yes
    
- name: node install packages
  tags: package
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - openstack-neutron 
    - openstack-neutron-linuxbridge 
    - ebtables
    - ipset
    - openstack-manila-share
    - python3-PyMySQL

- name: install manila configuration
  tags: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/manila/{{ item }}"
  with_items:
    - manila.conf

- name: install neutron configurations
  tags: config
  template:
   src: "{{ item }}.j2"
   dest: "/etc/neutron/{{ item }}"
  with_items:
    - neutron.conf

- name: install linuxbridge configurations
  tags: config
  template:
    src: "linuxbridge_agent.ini.j2"
    dest: "/etc/neutron/plugins/ml2/linuxbridge_agent.ini"

- name: Create directory /var/lib/manila
  file:
    path: /var/lib/manila
    state: directory
    owner: manila
    group: manila
    mode: 0755

- name: start services
  tags: service
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  when: not ansible_check_mode
  with_items:
    - openstack-manila-share
    - neutron-linuxbridge-agent
