- name: patch powertools repo
  replace:
    path: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
    regexp: '(\s+)enabled\=0(\s+.*)?$'
    replace: '\1enabled=1\2'
    backup: yes
    
- name: install packages
  tags: packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - openstack-nova-compute
    - sysfsutils

- name: install nova configuration
  tags: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nova/{{ item }}"
  with_items:
    - nova.conf

- name: install modprobe kvm
  tags: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/modprobe.d/{{ item }}"
  with_items:
    - kvm.conf
  when: virt_type == "kvm"

- name: install load kvm
  tags: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/modules-load.d/{{ item }}"
  with_items:
    - lkvm.conf
  when: virt_type == "kvm"

- name: start services
  tags: service
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  when: not ansible_check_mode
  with_items:
    - libvirtd
    - openstack-nova-compute
